#KROTKI TO LISTY, KTORYCH ZAWARTOSCI NIE MOZNA ZMIENIAC
#NIE POSIADAJA FUNKCJI SORTOWANIA, APPEND ITD.

#DEKLARACJA I UZUPELNIANIE DANYMI

krotka=("kawka","kawusia",33,[12,55,"koza"]) #UZYWAMY () NIE []
krotka2=tuple() #ODPOWIEDNIK lista=list()

#POBIERANIE WARTOSCI Z KROTEK
#IDENTYCZNIE JAK W PRZYPADKU LIST




